#! /bin/sh

# Variables
alias bc='bspc config'
alias br='bspc rule'

# Workspaces (two-monitor support)
if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
  bspc monitor eDP -d 1 2 3 4 &
  bspc monitor HDMI-A-0 -d 5 6 7 8 &
else
  bspc monitor eDP -d 1 2 3 4 5 6 7 8 &
fi

# Autostart
killall sxhkd; sxhkd &
killall picom; picom &
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh
nitrogen --restore &

# Other settings
bc border_width         2
bc window_gap           7
#bc focused_border_color '#a30822' #red
bc focused_border_color '#3538df' #blue
bc normal_border_color  '#454849'
bc split_ratio          0.50
bc top_padding		28
bc borderless_monocle   true
bc gapless_monocle      true

# Rules
br -a Xarchiver state=floating
